chore: release v0.1.1: more verbose output

diff --git a/wait-until b/wait-until
--- a/wait-until
+++ b/wait-until
@@ -3,14 +3,18 @@
 command="${1}"
 timeout="${2:-30}"
 
+echo -e "\n\n\n=Running: $command=\n\n"
+
 i=0
 until eval "${command}"
 do
-    sleep 1
-    ((i++))
+  sleep 1
+  ((i++))
 
-    if [ "${i}" -gt "${timeout}" ]; then
-        echo "command was never successful, aborting due to ${timeout}s timeout!"
-        exit 1
-    fi
+  if [ "${i}" -gt "${timeout}" ]; then
+      echo "command was never successful, aborting due to ${timeout}s timeout!"
+      exit 1
+  fi
 done
+
+echo -e "\n\n\n= Done successfully running: $command =\n\n"
